# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/DjangoVPS
    expose:
      - 8000
    env_file:
      - .env
    restart: always

  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/DjangoVPS/static
    depends_on:
      - web
    restart: always

volumes:
  static_volume: