services:
  web:
    build: .
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/DjangoVPS
      - static_volume:/DjangoVPS/static
      - media_volume:/DjangoVPS/media
    env_file:
      - .env
    expose:
      - "8000"

  nginx:
    image: nginx:1.21
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/DjangoVPS/static
      - media_volume:/DjangoVPS/media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: