# docker-compose.yml
services:
  web:
    build: .
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/DjangoVPS
    env_file:
      - .env
    expose:
      - "8000"
    restart: always

  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/DjangoVPS/static
      - media_volume:/DjangoVPS/media
    depends_on:
      - web
    restart: always

volumes:
  static_volume:
  media_volume: