services:
  web:
    build:
      context: ../
      dockerfile: Production/Dockerfile
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ../:/DjangoVPS
      - static_volume:/DjangoVPS/static
      - media_volume:/DjangoVPS/media
    env_file:
      - Production/.env
    expose:
      - "8000"

  nginx:
    image: nginx:1.21
    volumes:
      - Production/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/DjangoVPS/static
      - media_volume:/DjangoVPS/media
      - Production/certbot/conf:/etc/letsencrypt
      - Production/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - Production/certbot/conf:/etc/letsencrypt
      - Production/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  static_volume:
  media_volume: